# Generated by Django 2.1 on 2021-08-04 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 15, 8, 35, 937851, tzinfo=utc)),
        ),
    ]
